### ISSUE TITLE
GPUの使用率が低い・CPUのコア数設定ができるんだが，それがうまく機能していない 

### ISSUE THREAD

**Issue by kasukeinu** [hwip/synergy#10]

**Comment by kasukeinu** [comment]
学習してる途中にnvidia-smiを監視して動いて来るかをみる

怪しいのは
* if/forなどの生pythonの処理
* np.floatに型変換しているあたり

**Comment by NishiYusuke** [comment]
メモ:
パッと見た感じほとんどnumpyで処理してそう？
もしそうなら、gpu使う処理があんまり無いからって結論になる
余談だが、numpy を cupy に置き換えるだけで、速度上がるかも (やるとは言っていない)

**Comment by NishiYusuke** [comment]
原因 : CUDA toolkit が入っていなかったため
→ CUDA 10.0 インストールしてプログラム実行したところ、500MiBほどGPUメモリを使用していたので本件解決したと判断

**Comment by kasukeinu** [comment]
![image](https://user-images.githubusercontent.com/22784312/100968821-6a8cf300-3575-11eb-809b-685fe10abd59.png)

pythonのプロセスで動いているので行けてそうですね
同じIDでプロセスが２つになってるのが解せないんだけど…
@KazukiHigashi の承認次第で一旦閉じて，高速化のissue立てておきますか？
