### ISSUE TITLE
各試行 (step) の成否およびその時の把持姿勢 (actions : プログラムでは"u" と定義されてる)の取得場所

### ISSUE THREAD

**Issue by NishiYusuke** [hwip/synergy#15]
https://github.com/hwip/synergy/blob/644efac2f314dca692939b9182bb1ea5a649216b/baselines/her/rollout.py#L106-L108

**Comment by NishiYusuke** [comment]
※ RolloutWorker クラスの \_\_init\_\_ 直下に記載されているコメント内の Args から以下抜粋
> dims (dict of ints): the dimensions for observations (o), goals (g), and actions (u)
>             logger (object): the logger that is used by the rollout worker

上記を見る限り, self.envs[i].step()で引数として与えられている u[i] が行動 (actions) に相当している.

もし, 行動=把持姿勢の時系列ならば, 
if 'is_success' in info: 内が成功した場合に実行される if 文っぽいので, 
この if 文内で u[i][-1] など把持姿勢の時系列の一番最後の姿勢を取ってきて保存すれば, 
成功把持姿勢を抜き出せるかも? (わからんけど)

※メモ
[OpenAI のサンプル](https://openai.com/blog/ingredients-for-robotics-research/)を見る限り, env.stepの返り値は以下の通り. (詳細はあまり分かってない)
> obs, reward, done, info = env.step(action)

**Comment by TomohiroMOTODA** [comment]
https://github.com/hwip/synergy/blob/778fcd85bd16b04a080c641d4557f82c71b5fdfc/baselines/her/rollout.py#L127
if 'is_success' in info: は成功の有無に関係なく，入るみたいですね．
成否はsuccess[i] = info['is_success']に格納されていて，sucess[i] = 1 : 成功，success[i] = 0:  失敗 
当該箇所にif文を追加が必須かな．
