### ISSUE TITLE
学習に使用している報酬関数の場所について

### ISSUE THREAD

**Issue by kasukeinu** [hwip/synergy#9]
@KazukiHigashi 
`compute_reward`でレポジトリ全体を検索書けると，

- `fetch_env.py`
- `grasp_block.py`
- `manipulate.py`
- `reach.py`

の四箇所に`def compute_reward(hoge)`が定義されていて，どの部分が実際の学習で使っている報酬関数なのかが判断が付きませんでした．
どの部分か教えてもらえれば幸いです．

**Comment by KazukiHigashi** [comment]
grasp_block.pyが対象物把持タスクを記述している部分なので、その部分を参照してください。
また、GraspBlockEnvはManipulateクラスのcompute_rewardを継承していて、必要な情報はGraspBlockEnvクラスの[定義部分](https://github.com/hwip/synergy/blob/0e57c983466881895575dd45d50c0a65646fcef5/gym-grasp/gym_grasp/envs/hand/grasp_block.py#L305)で記述されているので、そちらを参考にしてください。
